export { default as Navbar } from './navbar/Navbar';
export { default as Login } from './auth/login/Login';
export { default as Register } from './auth/register/Register';
export { default as Dashboard } from './dashboard/Dashboard';
export { default as Posts } from './posts/Posts';
export { default as PostCard } from './postCard/PostCard';
export { default as NotFound } from './404/NotFound';
export { default as Footer } from './footer/Footer';
export { default as ErrorBoundary } from './errorBoundary/ErrorBoundary';
